const A=document.querySelector('#adminApp');
let data={events:[],submissions:[],places:[],partners:[],settings:{},dashboard:{}};
const api=async(u,o={})=>{const r=await fetch(u,o);if(r.status===401)throw new Error('AUTH');if(!r.ok)throw new Error(await r.text());return r.json()};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));

const mediaFields=[
 ['logo_dark','Logo nero / header'],
 ['logo_light','Logo bianco / footer'],
 ['hero_image','Foto principale Home'],
 ['category_feste_patronali','Categoria · Feste patronali'],
 ['category_sagre','Categoria · Sagre'],
 ['category_concerti','Categoria · Concerti'],
 ['category_cultura','Categoria · Cultura'],
 ['category_sport','Categoria · Sport'],
 ['category_bambini','Categoria · Bambini'],
 ['territory_marchesato','Territorio · Marchesato'],
 ['territory_crotone','Territorio · Provincia di Crotone'],
 ['territory_catanzaro','Territorio · Provincia di Catanzaro'],
 ['banner_mangiare','Banner · Dove mangiare'],
 ['banner_dormire','Banner · Dove dormire']
];

async function init(){try{await load();shell('dashboard')}catch(e){login()}}
function login(){A.innerHTML=`<div class="login"><form class="login-card" id="login"><img src="/assets/logo-black.png" style="width:220px;margin-bottom:25px"><h2>Area riservata</h2><div class="field"><label>Password</label><input type="password" name="password" required></div><button class="btn btn-dark" style="width:100%;margin-top:14px">Accedi</button></form></div>`;document.querySelector('#login').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});await load();shell('dashboard')}catch{alert('Password non valida')}}}
async function load(){const [d,e,s,p,pa,se]=await Promise.all([api('/api/admin/dashboard'),api('/api/admin/events'),api('/api/admin/submissions'),api('/api/admin/places'),api('/api/admin/partners'),api('/api/admin/settings')]);data={dashboard:d,events:e.items||[],submissions:s.items||[],places:p.items||[],partners:pa.items||[],settings:se.settings||{}}}
function shell(tab){A.innerHTML=`<div class="admin-shell"><header class="admin-top"><img src="${esc(data.settings.logo_light||'/assets/logo-white.png')}"><button class="btn btn-light" id="logout">Esci</button></header><div class="admin-wrap admin-grid"><nav class="admin-nav">${[['dashboard','Dashboard'],['events','Eventi'],['submissions','Segnalazioni'],['media','Foto e logo'],['places','Attività'],['partners','Partner']].map(x=>`<button data-tab="${x[0]}" class="${tab===x[0]?'active':''}">${x[1]}</button>`).join('')}</nav><main id="panel"></main></div></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>shell(b.dataset.tab));document.querySelector('#logout').onclick=async()=>{await api('/api/admin/logout',{method:'POST'}).catch(()=>{});login()};render(tab)}
function render(tab){const P=document.querySelector('#panel');if(tab==='dashboard')P.innerHTML=`<section class="panel"><h1>Dashboard</h1><div class="kpis"><div class="kpi"><span>Eventi</span><b>${data.dashboard.events||0}</b></div><div class="kpi"><span>Futuri</span><b>${data.dashboard.upcoming||0}</b></div><div class="kpi"><span>Da approvare</span><b>${data.dashboard.pending||0}</b></div><div class="kpi"><span>Attività</span><b>${data.dashboard.places||0}</b></div></div></section>`;if(tab==='events')events(P);if(tab==='submissions')subs(P);if(tab==='media')mediaManager(P);if(tab==='places')simpleCrud(P,'places','Attività');if(tab==='partners')simpleCrud(P,'partners','Partner')}

async function uploadImage(file){const fd=new FormData();fd.append('file',file);return api('/api/admin/upload',{method:'POST',body:fd})}

function mediaManager(P){P.innerHTML=`<section class="panel"><div class="section-head"><div><h1>Foto e logo</h1><p style="color:#666;margin:6px 0 0">Carica qui le immagini principali del sito. Le modifiche diventano visibili subito.</p></div></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px">${mediaFields.map(([key,label])=>`<article style="border:1px solid #e5e5e5;border-radius:18px;padding:14px"><div style="height:150px;border-radius:14px;overflow:hidden;background:#f2f2f2;display:grid;place-items:center;margin-bottom:12px"><img id="preview-${key}" src="${esc(data.settings[key]||'')}" alt="" style="width:100%;height:100%;object-fit:${key.startsWith('logo_')?'contain':'cover'};padding:${key.startsWith('logo_')?'18px':'0'}"></div><b>${label}</b><div class="field" style="margin-top:10px"><input type="file" accept="image/*" data-media-file="${key}"></div><button class="btn btn-dark" style="width:100%;margin-top:10px" data-media-save="${key}">Carica e usa</button></article>`).join('')}</div></section>`;
 document.querySelectorAll('[data-media-save]').forEach(btn=>btn.onclick=async()=>{const key=btn.dataset.mediaSave,input=document.querySelector(`[data-media-file="${key}"]`),file=input.files?.[0];if(!file)return alert('Seleziona prima un’immagine.');const old=btn.textContent;btn.disabled=true;btn.textContent='Caricamento…';try{const up=await uploadImage(file);await api('/api/admin/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,value:up.url})});data.settings[key]=up.url;document.querySelector(`#preview-${key}`).src=up.url;btn.textContent='Salvato ✓';setTimeout(()=>{btn.textContent=old;btn.disabled=false},1000)}catch(e){btn.disabled=false;btn.textContent=old;alert('Errore nel caricamento. Verifica il binding R2 MEDIA.')}})
}

function events(P){P.innerHTML=`<section class="panel"><div class="section-head"><h1>Eventi</h1><button class="btn btn-accent" id="newEvent">Nuovo evento</button></div><table class="admin-table"><thead><tr><th>Evento</th><th>Data</th><th>Comune</th><th></th></tr></thead><tbody>${data.events.map(e=>`<tr><td><b>${esc(e.title)}</b><br><small>${esc(e.category)}</small></td><td>${esc(e.start_date)}</td><td>${esc(e.city)}</td><td><button class="btn btn-outline edit-event" data-id="${e.id}">Modifica</button></td></tr>`).join('')}</tbody></table></section>`;document.querySelector('#newEvent').onclick=()=>eventForm();document.querySelectorAll('.edit-event').forEach(b=>b.onclick=()=>eventForm(data.events.find(e=>e.id==b.dataset.id)))}
function eventForm(e={}){document.querySelector('#panel').innerHTML=`<section class="panel"><h1>${e.id?'Modifica':'Nuovo'} evento</h1><form class="admin-like-form" id="eventForm"><div class="field"><label>Titolo</label><input name="title" value="${esc(e.title||'')}" required></div><div class="field"><label>Categoria</label><input name="category" value="${esc(e.category||'')}" required></div><div class="field"><label>Provincia</label><input name="province" value="${esc(e.province||'Crotone')}"></div><div class="field"><label>Area</label><input name="area" value="${esc(e.area||'Marchesato')}"></div><div class="field"><label>Comune</label><input name="city" value="${esc(e.city||'')}"></div><div class="field"><label>Località</label><input name="locality" value="${esc(e.locality||'')}"></div><div class="field"><label>Data inizio</label><input type="date" name="start_date" value="${esc(e.start_date||'')}" required></div><div class="field"><label>Data fine</label><input type="date" name="end_date" value="${esc(e.end_date||'')}"></div><div class="field full"><label>Foto evento</label><div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap"><input id="eventImageFile" type="file" accept="image/*"><button type="button" class="btn btn-outline" id="uploadEventImage">Carica foto</button></div><input type="hidden" name="image" id="eventImageUrl" value="${esc(e.image||'')}">${e.image?`<img id="eventImagePreview" src="${esc(e.image)}" style="margin-top:10px;width:220px;height:130px;object-fit:cover;border-radius:14px">`:'<img id="eventImagePreview" style="display:none;margin-top:10px;width:220px;height:130px;object-fit:cover;border-radius:14px">'}</div><div class="field full"><label>Descrizione</label><textarea name="description">${esc(e.description||'')}</textarea></div><div class="field"><label><input type="checkbox" name="featured" ${e.featured?'checked':''}> In evidenza</label></div><div class="field"><label><input type="checkbox" name="weekend" ${e.weekend?'checked':''}> Questo weekend</label></div><div class="field full"><button class="btn btn-accent">Salva</button></div></form></section>`;
 document.querySelector('#uploadEventImage').onclick=async()=>{const f=document.querySelector('#eventImageFile').files?.[0];if(!f)return alert('Seleziona una foto.');const b=document.querySelector('#uploadEventImage');b.disabled=true;b.textContent='Caricamento…';try{const up=await uploadImage(f);document.querySelector('#eventImageUrl').value=up.url;const pr=document.querySelector('#eventImagePreview');pr.src=up.url;pr.style.display='block';b.textContent='Caricata ✓'}catch{b.textContent='Carica foto';alert('Errore caricamento. Verifica R2 MEDIA.')}finally{b.disabled=false}};
 document.querySelector('#eventForm').onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(ev.target),obj=Object.fromEntries(fd);obj.featured=fd.has('featured')?1:0;obj.weekend=fd.has('weekend')?1:0;await api(e.id?`/api/admin/events/${e.id}`:'/api/admin/events',{method:e.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)});await load();shell('events')}}
function subs(P){P.innerHTML=`<section class="panel"><h1>Segnalazioni</h1><table class="admin-table"><thead><tr><th>Evento</th><th>Da</th><th>Data</th><th>Stato</th><th></th></tr></thead><tbody>${data.submissions.map(s=>`<tr><td><b>${esc(s.title)}</b><br><small>${esc(s.city)}</small></td><td>${esc(s.email)}</td><td>${esc(s.start_date)}</td><td>${esc(s.status)}</td><td>${s.status==='pending'?`<button class="btn btn-accent approve" data-id="${s.id}">Approva</button>`:''}</td></tr>`).join('')}</tbody></table></section>`;document.querySelectorAll('.approve').forEach(b=>b.onclick=async()=>{await api(`/api/admin/submissions/${b.dataset.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'approved',create_event:true})});await load();shell('submissions')})}
function simpleCrud(P,type,title){P.innerHTML=`<section class="panel"><div class="section-head"><h1>${title}</h1><button class="btn btn-accent" id="add">Aggiungi</button></div>${data[type].map(x=>`<div style="padding:14px 0;border-bottom:1px solid #eee"><b>${esc(x.name)}</b><br><small>${esc(x.city||x.description||'')}</small></div>`).join('')||'<div class="empty">Nessun elemento.</div>'}</section>`;document.querySelector('#add').onclick=()=>{const name=prompt('Nome');if(!name)return;api(`/api/admin/${type}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,type:type==='places'?'mangiare':undefined})}).then(async()=>{await load();shell(type)})}}
init();
