const A=document.querySelector('#adminApp');
const provinces=['Catanzaro','Cosenza','Crotone','Reggio Calabria','Vibo Valentia'];
const categories=['Feste patronali','Sagre','Concerti','Musica','Cultura','Tradizioni','Sport','Eventi per bambini','Enogastronomia','Fiere/Mercatini','Feste Locali'];
let data={dashboard:{},events:[],submissions:[],places:[],partners:[],territories:[],fields:[],settings:{}};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const api=async(u,o={})=>{const r=await fetch(u,o);if(r.status===401)throw new Error('AUTH');const txt=await r.text();let j={};try{j=JSON.parse(txt)}catch{}if(!r.ok)throw new Error(j.error||txt||'Errore');return j};
async function load(){const urls=['dashboard','events','submissions','places','partners','territories','submission-fields','settings'];const rs=await Promise.all(urls.map(x=>api('/api/admin/'+x)));data={dashboard:rs[0],events:rs[1].items||[],submissions:rs[2].items||[],places:rs[3].items||[],partners:rs[4].items||[],territories:rs[5].items||[],fields:rs[6].items||[],settings:rs[7]||{}}}
async function init(){try{await load();shell('dashboard')}catch(e){login()}}
function login(){A.innerHTML=`<div class="login"><form class="login-card" id="login"><a class="login-brand" href="/" aria-label="Torna alla home di Marchesato in Festa"><img src="/assets/logo-black.png" alt="Marchesato in Festa"></a><h2>Area riservata</h2><div class="field"><label>Password</label><input type="password" name="password" required></div><button class="btn btn-dark" style="width:100%;margin-top:14px">Accedi</button></form></div>`;document.querySelector('#login').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});await load();shell('dashboard')}catch{alert('Password non valida')}}}
const tabs=[['dashboard','Dashboard'],['events','Eventi'],['submissions','Segnalazioni'],['form','Modulo segnalazione'],['territories','Territorio'],['places','Mangiare / Dormire'],['partners','Partner'],['media','Foto e logo']];
function shell(tab){A.innerHTML=`<div class="admin-shell"><header class="admin-top"><a class="admin-brand" href="/" aria-label="Torna alla home di Marchesato in Festa"><img src="${esc(data.settings.logo_white||'/assets/logo-white.png')}" alt="Marchesato in Festa"></a><button class="btn btn-light" id="logout">Esci</button></header><div class="admin-wrap admin-grid"><nav class="admin-nav">${tabs.map(x=>`<button data-tab="${x[0]}" class="${tab===x[0]?'active':''}">${x[1]}</button>`).join('')}</nav><main id="panel"></main></div></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>shell(b.dataset.tab));document.querySelector('#logout').onclick=async()=>{await api('/api/admin/logout',{method:'POST'}).catch(()=>{});login()};render(tab)}
function render(tab){const P=document.querySelector('#panel');if(tab==='dashboard')dashboard(P);if(tab==='events')events(P);if(tab==='submissions')subs(P);if(tab==='form')formBuilder(P);if(tab==='territories')territories(P);if(tab==='places')places(P);if(tab==='partners')partners(P);if(tab==='media')media(P)}
function dashboard(P){P.innerHTML=`<section class="panel"><h1>Dashboard</h1><p>Da qui puoi modificare praticamente tutto il contenuto pubblico del sito.</p><div class="kpis"><div class="kpi"><span>Eventi</span><b>${data.dashboard.events||0}</b></div><div class="kpi"><span>Futuri</span><b>${data.dashboard.upcoming||0}</b></div><div class="kpi"><span>Da approvare</span><b>${data.dashboard.pending||0}</b></div><div class="kpi"><span>Attività</span><b>${data.dashboard.places||0}</b></div><div class="kpi"><span>Territori</span><b>${data.dashboard.territories||0}</b></div><div class="kpi"><span>Partner</span><b>${data.dashboard.partners||0}</b></div></div></section>`}
function rowButtons(kind,id){return `<button class="btn btn-outline edit" data-kind="${kind}" data-id="${id}">Modifica</button> <button class="btn btn-outline del" data-kind="${kind}" data-id="${id}">Elimina</button>`}
function events(P){P.innerHTML=`<section class="panel"><div class="section-head"><div><h1>Eventi</h1><p>Crea, modifica o elimina qualsiasi evento.</p></div><button class="btn btn-accent" id="new">Nuovo evento</button></div><table class="admin-table"><thead><tr><th>Evento</th><th>Data</th><th>Comune</th><th></th></tr></thead><tbody>${data.events.map(e=>`<tr><td><b>${esc(e.title)}</b><br><small>${esc(e.category)}</small></td><td>${esc(e.start_date)}</td><td>${esc(e.city)}</td><td>${rowButtons('events',e.id)}</td></tr>`).join('')}</tbody></table></section>`;document.querySelector('#new').onclick=()=>eventForm();bindEditDelete('events',id=>eventForm(data.events.find(x=>x.id==id)))}
function uploadField(name,value,label='Immagine'){return `<div class="field full"><label>${label}</label><div class="upload-row"><input name="${name}" value="${esc(value||'')}"><input type="file" accept="image/*" data-upload="${name}"><button type="button" class="btn btn-outline upload-btn" data-target="${name}">Carica</button></div>${value?`<img src="${esc(value)}" class="admin-upload-preview" alt="Anteprima ${esc(label)}">`:''}</div>`}
function provinceSelect(v=''){return `<select name="province">${provinces.map(p=>`<option ${p===v?'selected':''}>${p}</option>`).join('')}</select>`}
function categorySelect(v=''){return `<select name="category">${categories.map(p=>`<option ${p===v?'selected':''}>${p}</option>`).join('')}</select>`}
function parseEventAreas(raw=''){
  if(Array.isArray(raw)) return raw.map(String).filter(Boolean);
  if(!raw) return [];
  if(typeof raw==='string'){
    const value=raw.trim();
    if(!value)return [];
    try{const parsed=JSON.parse(value);if(Array.isArray(parsed))return parsed.map(String).filter(Boolean)}catch{}
    return value.split('|').map(x=>x.trim()).filter(Boolean);
  }
  return [];
}
function territoryMultiSelect(raw=''){
  const selected=parseEventAreas(raw);
  const available=[...data.territories].sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)||String(a.name||'').localeCompare(String(b.name||''),'it'));
  const options=available.map(t=>`<label class="territory-option"><input type="checkbox" value="${esc(t.name)}" ${selected.includes(String(t.name))?'checked':''}><span><b>${esc(t.name)}</b>${t.province?`<small>${esc(t.province)}</small>`:''}</span></label>`).join('');
  return `<div class="territory-multi" data-territory-multi><input type="hidden" name="area" value="${esc(JSON.stringify(selected))}"><button type="button" class="territory-multi-toggle"><span class="territory-multi-label">${selected.length?`${selected.length} territor${selected.length===1?'io':'i'} selezionat${selected.length===1?'o':'i'}`:'Seleziona territori'}</span><span class="territory-multi-arrow">⌄</span></button><div class="territory-multi-menu"><div class="territory-multi-options">${options||'<div class="territory-multi-empty">Crea prima almeno un territorio nella sezione Territorio.</div>'}</div></div><div class="territory-multi-selected"></div></div>`;
}
function bindTerritoryMultiSelect(root=document){
  root.querySelectorAll('[data-territory-multi]').forEach(box=>{
    const toggle=box.querySelector('.territory-multi-toggle'),menu=box.querySelector('.territory-multi-menu'),hidden=box.querySelector('input[name="area"]'),label=box.querySelector('.territory-multi-label'),selectedBox=box.querySelector('.territory-multi-selected');
    const checks=[...box.querySelectorAll('.territory-option input[type="checkbox"]')];
    const sync=()=>{
      const values=checks.filter(c=>c.checked).map(c=>c.value);
      hidden.value=JSON.stringify(values);
      label.textContent=values.length?`${values.length} territor${values.length===1?'io':'i'} selezionat${values.length===1?'o':'i'}`:'Seleziona territori';
      selectedBox.innerHTML=values.map(v=>`<span class="territory-selected-chip">${esc(v)}<button type="button" data-remove-territory="${esc(v)}" aria-label="Rimuovi ${esc(v)}">×</button></span>`).join('');
      selectedBox.querySelectorAll('[data-remove-territory]').forEach(btn=>btn.onclick=()=>{const c=checks.find(x=>x.value===btn.dataset.removeTerritory);if(c)c.checked=false;sync()});
    };
    toggle.onclick=()=>{box.classList.toggle('open');toggle.setAttribute('aria-expanded',box.classList.contains('open')?'true':'false')};
    checks.forEach(c=>c.addEventListener('change',sync));
    document.addEventListener('click',ev=>{if(!box.contains(ev.target)){box.classList.remove('open');toggle.setAttribute('aria-expanded','false')}});
    sync();
  });
}
function parseProgramDays(raw,startDate,endDate){
  if(Array.isArray(raw)) return raw;
  if(typeof raw==='string'&&raw.trim()){
    try{const p=JSON.parse(raw);if(Array.isArray(p))return p}catch{}
    if(startDate)return [{date:startDate,text:raw}];
  }
  return [];
}
function datesBetween(start,end){
  if(!start)return [];
  const a=new Date(start+'T12:00:00'),b=new Date((end||start)+'T12:00:00');
  if(Number.isNaN(a.getTime())||Number.isNaN(b.getTime())||b<a)return [start];
  const out=[];let d=new Date(a);let guard=0;
  while(d<=b&&guard<31){out.push(d.toISOString().slice(0,10));d.setDate(d.getDate()+1);guard++}
  return out;
}
function adminDateLabel(iso){
  if(!iso)return '';
  return new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(iso+'T12:00:00'));
}
function eventForm(e={}){
  const existingProgram=parseProgramDays(e.program,e.start_date,e.end_date);
  document.querySelector('#panel').innerHTML=`<section class="panel"><div class="section-head"><div><h1>${e.id?'Modifica evento':'Nuovo evento'}</h1><p>Tutte le informazioni della scheda evento.</p></div><button class="btn btn-outline" id="back">Indietro</button></div><form class="admin-like-form" id="f"><div class="field"><label>Titolo *</label><input name="title" value="${esc(e.title||'')}" required></div><div class="field"><label>Categoria *</label>${categorySelect(e.category)}</div><div class="field"><label>Provincia</label>${provinceSelect(e.province)}</div><div class="field"><label>Territorio / area</label>${territoryMultiSelect(e.area)}</div><div class="field"><label>Comune</label><input name="city" value="${esc(e.city||'')}"></div><div class="field"><label>Località</label><input name="locality" value="${esc(e.locality||'')}"></div><div class="field full"><label>Indirizzo</label><input name="address" value="${esc(e.address||'')}"></div><div class="field"><label>Data inizio *</label><input type="date" name="start_date" value="${esc(e.start_date||'')}" required></div><div class="field"><label>Data fine</label><input type="date" name="end_date" value="${esc(e.end_date||'')}"></div><div class="field"><label>Ora indicativa</label><input type="time" name="start_time" value="${esc(e.start_time||'')}"></div><div class="field"><label>Ingresso</label><select name="free"><option value="1" ${Number(e.free)!==0?'selected':''}>Gratuito</option><option value="0" ${Number(e.free)===0?'selected':''}>A pagamento</option></select></div>${uploadField('image',e.image,'Foto copertina')}${uploadField('poster_url',e.poster_url,'Locandina')}<div class="field full"><label>Descrizione</label><textarea name="description">${esc(e.description||'')}</textarea></div><div class="field full"><div class="program-admin-head"><div><label>Programma per giornata</label><small>Imposta data inizio e fine: qui comparirà automaticamente un riquadro per ogni giorno.</small></div></div><div id="programDays" class="program-admin-days"></div></div><div class="field"><label>Organizzatore</label><input name="organizer" value="${esc(e.organizer||'')}"></div><div class="field"><label>Telefono</label><input name="phone" value="${esc(e.phone||'')}"></div><div class="field"><label>Email</label><input type="email" name="email" value="${esc(e.email||'')}"></div><div class="field"><label>Social / sito</label><input name="social" value="${esc(e.social||'')}"></div><div class="field"><label><input type="checkbox" name="featured" ${e.featured?'checked':''}> In evidenza</label></div><div class="field full"><button class="btn btn-accent" type="submit">Salva evento</button></div></form></section>`;
  document.querySelector('#back').onclick=()=>shell('events');
  bindUploads();
  bindTerritoryMultiSelect(document.querySelector('#panel'));
  const f=document.querySelector('#f'),box=document.querySelector('#programDays');
  const renderProgramDays=()=>{
    const old={};box.querySelectorAll('[data-program-date]').forEach(x=>old[x.dataset.programDate]=x.value);
    const start=f.elements.start_date.value,end=f.elements.end_date.value||start;
    const days=datesBetween(start,end);
    if(!days.length){box.innerHTML='<div class="notice">Seleziona almeno la data di inizio per inserire il programma.</div>';return}
    box.innerHTML=days.map((date,i)=>{
      const previous=old[date] ?? existingProgram.find(x=>x.date===date)?.text ?? (existingProgram.length===1&&days.length===1?existingProgram[0].text:'');
      return `<section class="program-admin-day"><div class="program-admin-date"><span>${String(i+1).padStart(2,'0')}</span><div><b>${esc(adminDateLabel(date))}</b><small>${esc(date)}</small></div></div><textarea data-program-date="${date}" placeholder="Esempio:\n18:00 Apertura stand gastronomici\n21:30 Concerto in piazza">${esc(previous)}</textarea></section>`
    }).join('');
  };
  f.elements.start_date.addEventListener('change',renderProgramDays);
  f.elements.end_date.addEventListener('change',renderProgramDays);
  renderProgramDays();
  f.onsubmit=async ev=>{
    ev.preventDefault();
    const btn=f.querySelector('button[type="submit"]'),oldText=btn.textContent;
    try{
      btn.disabled=true;btn.textContent='Salvataggio...';
      const fd=new FormData(f),o=Object.fromEntries(fd);
      o.featured=fd.has('featured')?1:0;o.status='published';
      o.program=JSON.stringify([...box.querySelectorAll('[data-program-date]')].map(x=>({date:x.dataset.programDate,text:x.value.trim()})).filter(x=>x.text));
      await api(e.id?`/api/admin/events/${e.id}`:'/api/admin/events',{method:e.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(o)});
      await load();shell('events');setTimeout(()=>alert(e.id?'Evento aggiornato correttamente.':'Evento salvato e pubblicato correttamente.'),50);
    }catch(err){console.error('Errore salvataggio evento:',err);alert('Errore salvataggio evento: '+(err?.message||'errore sconosciuto'));btn.disabled=false;btn.textContent=oldText}
  };
}
function subs(P){P.innerHTML=`<section class="panel"><h1>Segnalazioni</h1><table class="admin-table"><thead><tr><th>Evento</th><th>Contatto</th><th>Data</th><th>Stato</th><th></th></tr></thead><tbody>${data.submissions.map(s=>`<tr><td><b>${esc(s.title)}</b><br><small>${esc(s.city)} · ${esc(s.province)}</small></td><td>${esc(s.email)}</td><td>${esc(s.start_date)}</td><td>${esc(s.status)}</td><td>${s.status==='pending'?`<button class="btn btn-accent approve" data-id="${s.id}">Approva</button>`:''} <button class="btn btn-outline del-sub" data-id="${s.id}">Elimina</button></td></tr>`).join('')}</tbody></table></section>`;document.querySelectorAll('.approve').forEach(b=>b.onclick=async()=>{await api(`/api/admin/submissions/${b.dataset.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'approved',create_event:true})});await load();shell('submissions')});document.querySelectorAll('.del-sub').forEach(b=>b.onclick=async()=>{if(confirm('Eliminare definitivamente questa segnalazione?')){await api(`/api/admin/submissions/${b.dataset.id}`,{method:'DELETE'});await load();shell('submissions')}})}
function formBuilder(P){P.innerHTML=`<section class="panel"><div class="section-head"><div><h1>Modulo “Segnala un evento”</h1><p>Puoi aggiungere, modificare, nascondere o eliminare i campi. Le 5 province calabresi sono sempre disponibili nel campo Provincia.</p></div><button class="btn btn-accent" id="newField">Nuovo campo</button></div><table class="admin-table"><thead><tr><th>Campo</th><th>Tipo</th><th>Obbligatorio</th><th>Attivo</th><th></th></tr></thead><tbody>${data.fields.map(f=>`<tr><td><b>${esc(f.label)}</b><br><small>${esc(f.field_key)}</small></td><td>${esc(f.field_type)}</td><td>${f.required?'Sì':'No'}</td><td>${f.active?'Sì':'No'}</td><td>${rowButtons('submission-fields',f.id)}</td></tr>`).join('')}</tbody></table></section>`;document.querySelector('#newField').onclick=()=>fieldForm();bindEditDelete('submission-fields',id=>fieldForm(data.fields.find(x=>x.id==id)))}
function fieldForm(f={}){document.querySelector('#panel').innerHTML=`<section class="panel"><h1>${f.id?'Modifica':'Nuovo'} campo</h1><form class="admin-like-form" id="f"><div class="field"><label>Chiave tecnica *</label><input name="field_key" value="${esc(f.field_key||'')}" ${f.id?'readonly':''} required></div><div class="field"><label>Etichetta *</label><input name="label" value="${esc(f.label||'')}" required></div><div class="field"><label>Tipo</label><select name="field_type">${['text','textarea','select','province','date','time','email','tel','url'].map(t=>`<option ${t===f.field_type?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label>Ordine</label><input type="number" name="sort_order" value="${esc(f.sort_order||0)}"></div><div class="field full"><label>Placeholder</label><input name="placeholder" value="${esc(f.placeholder||'')}"></div><div class="field full"><label>Opzioni select (separate da |)</label><input name="options" value="${esc(f.options||'')}"></div><div class="field"><label><input type="checkbox" name="required" ${f.required?'checked':''}> Obbligatorio</label></div><div class="field"><label><input type="checkbox" name="active" ${f.id?(f.active?'checked':''):'checked'}> Visibile</label></div><div class="field full"><button class="btn btn-accent">Salva</button></div></form></section>`;document.querySelector('#f').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),o=Object.fromEntries(fd);o.required=fd.has('required')?1:0;o.active=fd.has('active')?1:0;await api(f.id?`/api/admin/submission-fields/${f.id}`:'/api/admin/submission-fields',{method:f.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(o)});await load();shell('form')}}
function territories(P){P.innerHTML=`<section class="panel"><div class="section-head"><div><h1>Territorio</h1><p>Aggiungi o elimina aree e territori mostrati sul sito.</p></div><button class="btn btn-accent" id="new">Nuovo territorio</button></div>${cards(data.territories,'territories',x=>`${x.province||''}`)}</section>`;document.querySelector('#new').onclick=()=>territoryForm();bindEditDelete('territories',id=>territoryForm(data.territories.find(x=>x.id==id)))}
function territoryForm(x={}){genericForm('Territorio',x,'territories',`<div class="field"><label>Nome *</label><input name="name" value="${esc(x.name||'')}" required></div><div class="field"><label>Provincia</label>${provinceSelect(x.province)}</div><div class="field full"><label>Descrizione</label><textarea name="description">${esc(x.description||'')}</textarea></div>${uploadField('image',x.image,'Immagine territorio')}<div class="field"><label>Ordine</label><input type="number" name="sort_order" value="${esc(x.sort_order||0)}"></div><div class="field"><label><input type="checkbox" name="featured" ${x.featured?'checked':''}> In evidenza</label></div>`,'territories')}
function places(P){P.innerHTML=`<section class="panel"><div class="section-head"><div><h1>Dove mangiare e dormire</h1><p>Ogni attività ha una scheda pubblica cliccabile con tutte le informazioni.</p></div><button class="btn btn-accent" id="new">Nuova attività</button></div>${cards(data.places,'places',x=>`${x.type||''} · ${x.city||''}`)}</section>`;document.querySelector('#new').onclick=()=>placeForm();bindEditDelete('places',id=>placeForm(data.places.find(x=>x.id==id)))}
function placeForm(x={}){genericForm('Attività',x,'places',`<div class="field"><label>Nome *</label><input name="name" value="${esc(x.name||'')}" required></div><div class="field"><label>Tipologia</label><select name="type"><option value="mangiare" ${x.type==='mangiare'?'selected':''}>Mangiare</option><option value="dormire" ${x.type==='dormire'?'selected':''}>Dormire</option><option value="bere" ${x.type==='bere'?'selected':''}>Bere</option></select></div><div class="field"><label>Provincia</label>${provinceSelect(x.province)}</div><div class="field"><label>Comune</label><input name="city" value="${esc(x.city||'')}"></div><div class="field full"><label>Descrizione</label><textarea name="description">${esc(x.description||'')}</textarea></div>${uploadField('image',x.image,'Foto principale')}<div class="field full"><label>Indirizzo</label><input name="address" value="${esc(x.address||'')}"></div><div class="field"><label>Telefono</label><input name="phone" value="${esc(x.phone||'')}"></div><div class="field"><label>WhatsApp</label><input name="whatsapp" value="${esc(x.whatsapp||'')}"></div><div class="field"><label>Instagram</label><input name="instagram" value="${esc(x.instagram||'')}"></div><div class="field"><label>Sito</label><input name="website" value="${esc(x.website||'')}"></div><div class="field full"><label>Google Maps</label><input name="maps_url" value="${esc(x.maps_url||'')}"></div>`,'places')}
function partners(P){P.innerHTML=`<section class="panel"><div class="section-head"><div><h1>Partner e sponsor</h1><p>Ogni partner ha una pagina pubblica dedicata.</p></div><button class="btn btn-accent" id="new">Nuovo partner</button></div>${cards(data.partners,'partners',x=>x.level||'Partner')}</section>`;document.querySelector('#new').onclick=()=>partnerForm();bindEditDelete('partners',id=>partnerForm(data.partners.find(x=>x.id==id)))}
function partnerForm(x={}){genericForm('Partner',x,'partners',`<div class="field"><label>Nome *</label><input name="name" value="${esc(x.name||'')}" required></div><div class="field"><label>Livello</label><select name="level"><option value="partner" ${x.level==='partner'?'selected':''}>Partner</option><option value="main" ${x.level==='main'?'selected':''}>Main Partner</option><option value="sponsor" ${x.level==='sponsor'?'selected':''}>Sponsor</option></select></div><div class="field full"><label>Descrizione</label><textarea name="description">${esc(x.description||'')}</textarea></div>${uploadField('logo',x.logo,'Logo')}${uploadField('image',x.image,'Foto / copertina')}<div class="field"><label>Sito</label><input name="website" value="${esc(x.website||'')}"></div><div class="field"><label>Instagram</label><input name="instagram" value="${esc(x.instagram||'')}"></div><div class="field"><label>Telefono</label><input name="phone" value="${esc(x.phone||'')}"></div><div class="field"><label>Email</label><input type="email" name="email" value="${esc(x.email||'')}"></div><div class="field full"><label>Indirizzo</label><input name="address" value="${esc(x.address||'')}"></div><div class="field"><label>WhatsApp</label><input name="whatsapp" value="${esc(x.whatsapp||'')}"></div><div class="field"><label>Facebook</label><input name="facebook" value="${esc(x.facebook||'')}"></div><div class="field full"><label>Google Maps</label><input name="maps_url" value="${esc(x.maps_url||'')}"></div>`,'partners')}
function cards(items,kind,meta){return `<div style="display:grid;gap:12px">${items.map(x=>`<div style="display:grid;grid-template-columns:100px 1fr auto;gap:14px;align-items:center;padding:12px;border:1px solid #eee;border-radius:16px"><img src="${esc(x.image||x.logo||'/assets/logo-black.png')}" style="width:100px;height:72px;object-fit:cover;border-radius:12px;background:#f5f5f5"><div><b>${esc(x.name)}</b><br><small>${esc(meta(x))}</small></div><div>${rowButtons(kind,x.id)}</div></div>`).join('')||'<div class="empty">Nessun elemento.</div>'}</div>`}
function genericForm(title,x,type,html,back){document.querySelector('#panel').innerHTML=`<section class="panel"><div class="section-head"><h1>${x.id?'Modifica':'Nuovo'} ${title}</h1><button class="btn btn-outline" id="back">Indietro</button></div><form class="admin-like-form" id="f">${html}<div class="field full"><button class="btn btn-accent">Salva</button></div></form></section>`;document.querySelector('#back').onclick=()=>shell(back);bindUploads();document.querySelector('#f').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),o=Object.fromEntries(fd);if(type==='territories')o.featured=fd.has('featured')?1:0;await api(x.id?`/api/admin/${type}/${x.id}`:`/api/admin/${type}`,{method:x.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(o)});await load();shell(back)}}
function media(P){const items=[['logo_black','Logo nero / header','/assets/logo-black.png'],['logo_white','Logo bianco / footer','/assets/logo-white.png'],['hero_image','Foto principale Home','https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1600&q=80'],['eat_banner','Banner Dove mangiare','https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80'],['sleep_banner','Banner Dove dormire','https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1200&q=80'],...categories.map(c=>['cat_'+c.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,''),'Categoria: '+c,''])];P.innerHTML=`<section class="panel"><h1>Foto e logo</h1><p>Carica e sostituisci le immagini principali del sito.</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px">${items.map(([k,l,f])=>`<div style="border:1px solid #eee;border-radius:18px;padding:14px"><img src="${esc(data.settings[k]||f)}" style="width:100%;height:150px;object-fit:contain;background:#f6f6f6;border-radius:12px"><h3>${l}</h3><input type="file" accept="image/*" data-media="${k}"><button class="btn btn-dark media-upload" data-key="${k}" style="width:100%;margin-top:10px">Carica e usa</button></div>`).join('')}</div></section>`;document.querySelectorAll('.media-upload').forEach(b=>b.onclick=async()=>{const file=document.querySelector(`[data-media="${b.dataset.key}"]`).files[0];if(!file)return alert('Scegli un file');const u=await upload(file);await api('/api/admin/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({[b.dataset.key]:u.url})});await load();shell('media')})}
async function upload(file){const fd=new FormData();fd.append('file',file);return api('/api/admin/upload',{method:'POST',body:fd})}
function bindUploads(){document.querySelectorAll('.upload-btn').forEach(b=>b.onclick=async()=>{const target=b.dataset.target,file=document.querySelector(`[data-upload="${target}"]`).files[0];if(!file)return alert('Scegli un file');b.disabled=true;b.textContent='Caricamento...';try{const u=await upload(file);document.querySelector(`[name="${target}"]`).value=u.url;b.textContent='Caricato ✓'}catch(e){alert(e.message);b.textContent='Carica'}b.disabled=false})}
function bindEditDelete(kind,editFn){document.querySelectorAll(`.edit[data-kind="${kind}"]`).forEach(b=>b.onclick=()=>editFn(b.dataset.id));document.querySelectorAll(`.del[data-kind="${kind}"]`).forEach(b=>b.onclick=async()=>{if(!confirm('Eliminare definitivamente questo elemento?'))return;await api(`/api/admin/${kind}/${b.dataset.id}`,{method:'DELETE'});await load();shell(kind==='submission-fields'?'form':kind)})}
init();
