const enc=new TextEncoder();
const json=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json; charset=utf-8',...h}});
const bad=(m,s=400)=>json({error:m},s);
const slugify=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90);
async function hmac(secret,msg){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,enc.encode(msg));return btoa(String.fromCharCode(...new Uint8Array(sig))).replace(/=+$/,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function session(env){const exp=Date.now()+43200000,p=`admin.${exp}`,sig=await hmac(env.SESSION_SECRET||'change-me',p);return `${p}.${sig}`}
async function isAdmin(req,env){const m=(req.headers.get('cookie')||'').match(/mif_session=([^;]+)/);if(!m)return false;const p=m[1].split('.');if(p.length!==3||p[0]!=='admin'||Number(p[1])<Date.now())return false;return await hmac(env.SESSION_SECRET||'change-me',`admin.${p[1]}`)===p[2]}
async function body(req){try{return await req.json()}catch{return{}}}
async function must(req,env){return await isAdmin(req,env)?null:bad('Non autorizzato',401)}
async function uniqueSlug(env,title,date,id){const base=slugify(`${title}-${(date||'').slice(0,4)}`)||`evento-${Date.now()}`;let s=base,n=2;for(;;){const r=await env.DB.prepare('SELECT id FROM events WHERE slug=?').bind(s).first();if(!r||String(r.id)===String(id||''))return s;s=`${base}-${n++}`}}
const eventPayload=o=>({title:o.title||'',category:o.category||'',area:o.area||'',province:o.province||'',city:o.city||'',locality:o.locality||'',address:o.address||'',start_date:o.start_date||'',end_date:o.end_date||o.start_date||'',start_time:o.start_time||'',description:o.description||'',program:typeof o.program==='string'?o.program:JSON.stringify(o.program||[]),organizer:o.organizer||'',phone:o.phone||'',email:o.email||'',social:o.social||'',image:o.image||o.poster_url||'',poster_url:o.poster_url||'',free:Number(o.free??(o.price_type!=='A pagamento')),featured:Number(o.featured||0),weekend:Number(o.weekend||0),status:o.status||'published'});
async function ensureTables(env){await env.DB.batch([
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS territories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,province TEXT NOT NULL DEFAULT '',description TEXT DEFAULT '',image TEXT DEFAULT '',featured INTEGER DEFAULT 0,sort_order INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS submission_fields(id INTEGER PRIMARY KEY AUTOINCREMENT,field_key TEXT UNIQUE NOT NULL,label TEXT NOT NULL,field_type TEXT NOT NULL DEFAULT 'text',placeholder TEXT DEFAULT '',required INTEGER DEFAULT 0,active INTEGER DEFAULT 1,sort_order INTEGER DEFAULT 0,options TEXT DEFAULT '')`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS site_settings(key TEXT PRIMARY KEY,value TEXT DEFAULT '',updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS submission_payloads(submission_id INTEGER PRIMARY KEY,payload TEXT DEFAULT '{}')`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS partner_profiles(partner_id INTEGER PRIMARY KEY,phone TEXT DEFAULT '',email TEXT DEFAULT '',address TEXT DEFAULT '',whatsapp TEXT DEFAULT '',facebook TEXT DEFAULT '',maps_url TEXT DEFAULT '')`)
]);}
async function sendNotify(env,s){if(!env.RESEND_API_KEY||!env.NOTIFY_EMAIL)return;await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:env.FROM_EMAIL||'Marchesato in Festa <onboarding@resend.dev>',to:[env.NOTIFY_EMAIL],subject:`Nuova segnalazione: ${s.title||'Evento'}`,html:`<h2>Nuova segnalazione</h2><p><b>${s.title||''}</b></p><p>${s.city||''} — ${s.start_date||''}</p><p>${s.email||''}</p>`})}).catch(()=>{})}
const placeCols=['name','type','city','province','description','image','address','phone','whatsapp','instagram','website','maps_url'];
const partnerCols=['name','description','logo','image','website','instagram','level'];
const territoryCols=['name','province','description','image','featured','sort_order'];
const fieldCols=['field_key','label','field_type','placeholder','required','active','sort_order','options'];
function vals(o,cols){return cols.map(c=>o[c]??(c==='featured'||c==='sort_order'||c==='required'||c==='active'?0:''))}
export async function onRequest({request,env,params}){
 if(!env.DB)return bad('Binding D1 DB non configurato',503);await ensureTables(env);
 const url=new URL(request.url),method=request.method.toUpperCase(),path='/' + ((params.path)||[]).join('/');
 try{
  if(method==='GET'&&path==='/events'){const r=await env.DB.prepare("SELECT * FROM events WHERE status='published' ORDER BY start_date ASC, featured DESC").all();return json({items:r.results||[]})}
  if(method==='GET'&&path.startsWith('/events/')){const r=await env.DB.prepare("SELECT * FROM events WHERE slug=? AND status='published'").bind(decodeURIComponent(path.split('/').pop())).first();return r?json(r):bad('Evento non trovato',404)}
  if(method==='GET'&&path==='/places'){const r=await env.DB.prepare('SELECT * FROM places ORDER BY name').all();return json({items:r.results||[]})}
  if(method==='GET'&&path.match(/^\/places\/\d+$/)){const r=await env.DB.prepare('SELECT * FROM places WHERE id=?').bind(Number(path.split('/').pop())).first();return r?json(r):bad('Attività non trovata',404)}
  if(method==='GET'&&path==='/partners'){const r=await env.DB.prepare('SELECT * FROM partners ORDER BY id DESC').all();return json({items:r.results||[]})}
  if(method==='GET'&&path.match(/^\/partners\/\d+$/)){const r=await env.DB.prepare(`SELECT p.*,COALESCE(pp.phone,'') phone,COALESCE(pp.email,'') email,COALESCE(pp.address,'') address,COALESCE(pp.whatsapp,'') whatsapp,COALESCE(pp.facebook,'') facebook,COALESCE(pp.maps_url,'') maps_url FROM partners p LEFT JOIN partner_profiles pp ON pp.partner_id=p.id WHERE p.id=?`).bind(Number(path.split('/').pop())).first();return r?json(r):bad('Partner non trovato',404)}
  if(method==='GET'&&path==='/territories'){const r=await env.DB.prepare('SELECT * FROM territories ORDER BY sort_order ASC,name ASC').all();return json({items:r.results||[]})}
  if(method==='GET'&&path.match(/^\/territories\/\d+$/)){const r=await env.DB.prepare('SELECT * FROM territories WHERE id=?').bind(Number(path.split('/').pop())).first();return r?json(r):bad('Territorio non trovato',404)}
  if(method==='GET'&&path==='/submission-fields'){const r=await env.DB.prepare('SELECT * FROM submission_fields WHERE active=1 ORDER BY sort_order,id').all();return json({items:r.results||[]})}
  if(method==='GET'&&path==='/settings'){const r=await env.DB.prepare('SELECT key,value FROM site_settings').all();return json(Object.fromEntries((r.results||[]).map(x=>[x.key,x.value])))}
  if(method==='GET'&&path.startsWith('/media/')){if(!env.MEDIA)return bad('R2 non configurato',404);const k=decodeURIComponent(path.slice(7)),o=await env.MEDIA.get(k);if(!o)return bad('File non trovato',404);const h=new Headers();o.writeHttpMetadata(h);h.set('etag',o.httpEtag);h.set('cache-control','public,max-age=31536000,immutable');return new Response(o.body,{headers:h})}
  if(method==='POST'&&path==='/submissions'){const o=await body(request);if(!o.title||!o.email||!o.start_date||!o.city)return bad('Titolo, email, data e comune sono obbligatori');const fixed=['title','category','province','city','locality','address','start_date','end_date','start_time','price_type','description','program_text','organizer','phone','email','social','poster_url'];const v=fixed.map(c=>o[c]||'');const ins=await env.DB.prepare(`INSERT INTO submissions(${fixed.join(',')}) VALUES(${fixed.map(()=>'?').join(',')})`).bind(...v).run();const sid=ins.meta?.last_row_id; if(sid) await env.DB.prepare('INSERT OR REPLACE INTO submission_payloads(submission_id,payload) VALUES(?,?)').bind(sid,JSON.stringify(o)).run();await sendNotify(env,o);return json({ok:true},201)}
  if(method==='POST'&&path==='/admin/login'){const o=await body(request);if(!env.ADMIN_PASSWORD||o.password!==env.ADMIN_PASSWORD)return bad('Password non valida',401);return json({ok:true},200,{'set-cookie':`mif_session=${await session(env)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=43200`})}
  if(method==='POST'&&path==='/admin/logout')return json({ok:true},200,{'set-cookie':'mif_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0'});
  if(path.startsWith('/admin/')){const d=await must(request,env);if(d)return d}
  if(method==='GET'&&path==='/admin/dashboard'){const q=async s=>(await env.DB.prepare(s).first())?.c||0;return json({events:await q('SELECT COUNT(*) c FROM events'),upcoming:await q("SELECT COUNT(*) c FROM events WHERE start_date>=date('now') AND status='published'"),pending:await q("SELECT COUNT(*) c FROM submissions WHERE status='pending'"),places:await q('SELECT COUNT(*) c FROM places'),partners:await q('SELECT COUNT(*) c FROM partners'),territories:await q('SELECT COUNT(*) c FROM territories')})}
  if(method==='GET'&&path==='/admin/events'){const r=await env.DB.prepare('SELECT * FROM events ORDER BY start_date DESC').all();return json({items:r.results||[]})}
  if(method==='POST'&&path==='/admin/events'){const o=eventPayload(await body(request));if(!o.title||!o.start_date||!o.category)return bad('Titolo, categoria e data obbligatori');const slug=await uniqueSlug(env,o.title,o.start_date),cols=['slug',...Object.keys(o)];await env.DB.prepare(`INSERT INTO events(${cols.join(',')}) VALUES(${cols.map(()=>'?').join(',')})`).bind(slug,...Object.values(o)).run();return json({ok:true},201)}
  if(path.match(/^\/admin\/events\/\d+$/)){const id=Number(path.split('/').pop());if(method==='PATCH'){const o=eventPayload(await body(request)),slug=await uniqueSlug(env,o.title,o.start_date,id),cols=['slug',...Object.keys(o)];await env.DB.prepare(`UPDATE events SET ${cols.map(c=>`${c}=?`).join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(slug,...Object.values(o),id).run();return json({ok:true})}if(method==='DELETE'){await env.DB.prepare('DELETE FROM events WHERE id=?').bind(id).run();return json({ok:true})}}
  if(method==='GET'&&path==='/admin/submissions'){const r=await env.DB.prepare(`SELECT s.*,COALESCE(sp.payload,'{}') payload FROM submissions s LEFT JOIN submission_payloads sp ON sp.submission_id=s.id ORDER BY s.created_at DESC`).all();return json({items:r.results||[]})}
  if(path.match(/^\/admin\/submissions\/\d+$/)){const id=Number(path.split('/').pop());if(method==='DELETE'){await env.DB.batch([env.DB.prepare('DELETE FROM submission_payloads WHERE submission_id=?').bind(id),env.DB.prepare('DELETE FROM submissions WHERE id=?').bind(id)]);return json({ok:true})}if(method==='PATCH'){const o=await body(request),s=await env.DB.prepare('SELECT * FROM submissions WHERE id=?').bind(id).first();if(!s)return bad('Segnalazione non trovata',404);if(o.create_event&&o.status==='approved'){const ev=eventPayload({...s,area:s.province,image:s.poster_url,free:s.price_type!=='A pagamento'}),slug=await uniqueSlug(env,ev.title,ev.start_date),cols=['slug',...Object.keys(ev)];await env.DB.prepare(`INSERT INTO events(${cols.join(',')}) VALUES(${cols.map(()=>'?').join(',')})`).bind(slug,...Object.values(ev)).run()}await env.DB.prepare('UPDATE submissions SET status=? WHERE id=?').bind(o.status||'pending',id).run();return json({ok:true})}}
  if(method==='GET'&&path==='/admin/partners'){const r=await env.DB.prepare(`SELECT p.*,COALESCE(pp.phone,'') phone,COALESCE(pp.email,'') email,COALESCE(pp.address,'') address,COALESCE(pp.whatsapp,'') whatsapp,COALESCE(pp.facebook,'') facebook,COALESCE(pp.maps_url,'') maps_url FROM partners p LEFT JOIN partner_profiles pp ON pp.partner_id=p.id ORDER BY p.id DESC`).all();return json({items:r.results||[]})}
  if(method==='POST'&&path==='/admin/partners'){const o=await body(request);if(!o.name)return bad('Nome obbligatorio');const r=await env.DB.prepare('INSERT INTO partners(name,description,logo,image,website,instagram,level) VALUES(?,?,?,?,?,?,?)').bind(...vals(o,partnerCols)).run();const id=r.meta?.last_row_id;if(id)await env.DB.prepare('INSERT OR REPLACE INTO partner_profiles(partner_id,phone,email,address,whatsapp,facebook,maps_url) VALUES(?,?,?,?,?,?,?)').bind(id,o.phone||'',o.email||'',o.address||'',o.whatsapp||'',o.facebook||'',o.maps_url||'').run();return json({ok:true},201)}
  if(path.match(/^\/admin\/partners\/\d+$/)){const id=Number(path.split('/').pop());if(method==='PATCH'){const o=await body(request);await env.DB.prepare(`UPDATE partners SET ${partnerCols.map(c=>`${c}=?`).join(',')} WHERE id=?`).bind(...vals(o,partnerCols),id).run();await env.DB.prepare('INSERT INTO partner_profiles(partner_id,phone,email,address,whatsapp,facebook,maps_url) VALUES(?,?,?,?,?,?,?) ON CONFLICT(partner_id) DO UPDATE SET phone=excluded.phone,email=excluded.email,address=excluded.address,whatsapp=excluded.whatsapp,facebook=excluded.facebook,maps_url=excluded.maps_url').bind(id,o.phone||'',o.email||'',o.address||'',o.whatsapp||'',o.facebook||'',o.maps_url||'').run();return json({ok:true})}if(method==='DELETE'){await env.DB.batch([env.DB.prepare('DELETE FROM partner_profiles WHERE partner_id=?').bind(id),env.DB.prepare('DELETE FROM partners WHERE id=?').bind(id)]);return json({ok:true})}}
  const resources={places:{cols:placeCols},territories:{cols:territoryCols},'submission-fields':{cols:fieldCols}};
  for(const [res,cfg] of Object.entries(resources)){
   if(method==='GET'&&path===`/admin/${res}`){const order=res==='territories'?'sort_order ASC,name ASC':res==='submission-fields'?'sort_order ASC,id ASC':'id DESC';const r=await env.DB.prepare(`SELECT * FROM ${res.replace('-','_')} ORDER BY ${order}`).all();return json({items:r.results||[]})}
   if(method==='POST'&&path===`/admin/${res}`){const o=await body(request);if((res!=='submission-fields'&&!o.name)||(res==='submission-fields'&&(!o.field_key||!o.label)))return bad('Campi obbligatori mancanti');const table=res.replace('-','_');await env.DB.prepare(`INSERT INTO ${table}(${cfg.cols.join(',')}) VALUES(${cfg.cols.map(()=>'?').join(',')})`).bind(...vals(o,cfg.cols)).run();return json({ok:true},201)}
   const re=new RegExp(`^/admin/${res}/\\d+$`);if(path.match(re)){const id=Number(path.split('/').pop()),table=res.replace('-','_');if(method==='PATCH'){const o=await body(request);await env.DB.prepare(`UPDATE ${table} SET ${cfg.cols.map(c=>`${c}=?`).join(',')} WHERE id=?`).bind(...vals(o,cfg.cols),id).run();return json({ok:true})}if(method==='DELETE'){await env.DB.prepare(`DELETE FROM ${table} WHERE id=?`).bind(id).run();return json({ok:true})}}
  }
  if(method==='GET'&&path==='/admin/settings'){const r=await env.DB.prepare('SELECT key,value FROM site_settings').all();return json(Object.fromEntries((r.results||[]).map(x=>[x.key,x.value])))}
  if(method==='PATCH'&&path==='/admin/settings'){const o=await body(request);for(const [k,v] of Object.entries(o))await env.DB.prepare(`INSERT INTO site_settings(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).bind(k,String(v??'')).run();return json({ok:true})}
  if(method==='POST'&&path==='/admin/upload'){if(!env.MEDIA)return bad('Binding R2 MEDIA non configurato',503);const f=(await request.formData()).get('file');if(!(f instanceof File))return bad('File mancante');if(f.size>10*1024*1024)return bad('Max 10 MB');if(!/^image\//.test(f.type))return bad('Solo immagini');const ext=(f.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase(),key=`uploads/${Date.now()}-${crypto.randomUUID()}.${ext}`;await env.MEDIA.put(key,f.stream(),{httpMetadata:{contentType:f.type}});return json({url:`/api/media/${encodeURIComponent(key)}`,key},201)}
  return bad('Endpoint non trovato',404)
 }catch(e){console.error(e);return bad(e.message||'Errore interno',500)}
}
